# Generated by Django 4.0.4 on 2022-05-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cycle', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('menu1', models.CharField(blank=True, max_length=100, null=True)),
                ('menu2', models.CharField(blank=True, max_length=100, null=True)),
                ('menu3', models.CharField(blank=True, max_length=100, null=True)),
                ('menu4', models.CharField(blank=True, max_length=100, null=True)),
                ('menu5', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
