# Generated by Django 4.0.4 on 2022-05-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cycle',
            field=models.CharField(choices=[('조식', '조식'), ('중식', '중식'), ('석식', '석식')], max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='location',
            field=models.CharField(choices=[('칠성병사식당', '칠성병사식당'), ('보라매병사식당', '보라매병사식당'), ('독수리회관', '독수리회관'), ('다미정', '다미정'), ('보라매식당', '보라매식당')], max_length=100),
        ),
    ]
